CREATE TABLE `Users` (
	`UserID` INT NOT NULL AUTO_INCREMENT,
	`fname` VARCHAR(20) NOT NULL AUTO_INCREMENT,
	`mi` VARCHAR(1) AUTO_INCREMENT,
	`lname` VARCHAR(20) NOT NULL AUTO_INCREMENT,
	`public_key` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`UserID`)
);

CREATE TABLE `Block` (
	`blockID` INT(200) NOT NULL AUTO_INCREMENT,
	`hash_val` VARCHAR(64) NOT NULL,
	`prev_hash` VARCHAR(64) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	`nonce` INT(32) NOT NULL,
	`numtx` INT NOT NULL,
	`MerkleRoot` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`blockID`)
);

CREATE TABLE `MerkleTree` (

);

CREATE TABLE `Accounts` (
	`AccountID` BINARY NOT NULL AUTO_INCREMENT,
	`UserID` INT NOT NULL,
	`value` FLOAT NOT NULL,
	`CoinID` INT NOT NULL,
	`dateCreated` TIMESTAMP NOT NULL,
	`status` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`AccountID`)
);

CREATE TABLE `Coin` (
	`CoinID` INT NOT NULL AUTO_INCREMENT,
	`CoinName` VARCHAR(64) NOT NULL AUTO_INCREMENT,
	`RootBlock` VARCHAR(64) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`CoinID`)
);

ALTER TABLE `Accounts` ADD CONSTRAINT `Accounts_fk0` FOREIGN KEY (`UserID`) REFERENCES `Users`(`UserID`);

ALTER TABLE `Accounts` ADD CONSTRAINT `Accounts_fk1` FOREIGN KEY (`CoinID`) REFERENCES `Coin`(`CoinID`);

ALTER TABLE `Coin` ADD CONSTRAINT `Coin_fk0` FOREIGN KEY (`RootBlock`) REFERENCES `Block`(`blockID`);
